server:
  port: ${server-port:8081}
  servlet: 
    context-path: /api
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/${database-name:project_test}
    username: ${database-username:root}
    password: ${database-password:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    template:
      exchange: ${rabbitmq-default-exchange:transaction}
      routing-key: ${rabbitmq-default-routekey:my-routing-key}