server:
  port: ${server-port}
  servlet: 
    context-path: /api
spring: 
  datasource:
    url: ${database-url}/${database-name}
    username: ${database-username}
    password: ${database-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: ${show-sql}
    hibernate:
      ddl-auto: ${ddl-auto}
  sql:
    init:
      mode: always
      schema-locations:
      - classpath:/schema.sql
      continue-on-error: true
  rabbitmq:
    template:
      exchange: ${rabbitmq-default-exchange}
      routing-key: ${rabbitmq-default-routekey}
transaction:
  application:
    backend-url: ${backend-url}