server:
  port: ${server-port}
  servlet: 
    context-path: /api
spring: 
  datasource:
    url: ${database-url}/${database-name}
    username: ${database-username}
    password: ${database-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: ${show-sql}
    hibernate:
      ddl-auto: ${ddl-auto}
  rabbitmq:
    template:
      exchange: ${rabbitmq-default-exchange}
      routing-key: ${rabbitmq-default-routekey}